version: '3.1'

services:
    db:
      image: postgres
      restart: always
      env_file:
        - .env
      ports:
        - "5432:5432"
    redis:
      image: redis
    server:
      build: .
      restart: always
      env_file:
        - .env
      ports:
        - "9999:8000"
      depends_on:
        - db
        - redis
      volumes:
        - .:/app
    celery:
      build:
        context: .
      env_file:
        - .env
      volumes:
        - ./src/email:/app/email
      command: ["/app/src/celery.sh", "celery"]
      depends_on:
        redis:
          condition: service_started
    flower:
      build:
        context: .
      env_file:
        - .env
      command: ["/app/src/celery.sh", "flower"]
      depends_on:
        redis:
          condition: service_started
        celery:
          condition: service_started
      ports:
        - 8888:5555